---
- hosts: dockerhost
  tasks:
  - name: stop existing container
    command: docker stop regapp-server
    ignore_errors: yes
    

  - name: remove container
    command: docker rm regapp-server
    ignore_errors: yes

  - name: remove image
    command: docker rmi danielegambino/regapp:latest
    ignore_errors: yes

  - name: create container from Docker Hub
    command: docker run -d --name regapp-server -p 8085:8080 danielegambino/regapp:latest
