apiVersion: v1
kind: Service
metadata:
  name: demo-service

spec:
  selector:
    app: demo-app

  ports:
    - name: nginx-port
      protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer